[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
NFTCoupon = "3YS5kavc43aN36bzhwnz8YncufRVQM1ZMwPiceCUH4jU"

[programs.localnet]
NFTCoupon = "3YS5kavc43aN36bzhwnz8YncufRVQM1ZMwPiceCUH4jU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ayushsrivastava/.config/solana/id.json"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
